# Generated by Django 4.2.7 on 2025-04-11 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='found_time',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='storage_location',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='lost_time',
        ),
        migrations.AddField(
            model_name='founditem',
            name='scheduled_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFYING', 'Verifying'), ('CLAIMED', 'Claimed'), ('DONATED', 'Donated')], default='REPORTED', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFYING', 'Verifying'), ('CLAIMED', 'Claimed'), ('DONATED', 'Donated')], default='REPORTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='contact_reward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
