# Generated by Django 4.2.7 on 2025-04-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_verificationquestion_remove_founditem_found_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='unique_identifiers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='unique_identifiers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
