# Generated by Django 4.2.7 on 2025-04-12 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_founditem_brand_founditem_color_founditem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='founditem',
            name='custody_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='donation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('FOUND_WAITING', 'Found, Waiting for Owner'), ('IN_CUSTODY', 'In Custody'), ('DONATED', 'Donated'), ('CLAIMED', 'Claimed')], default='FOUND_WAITING', max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.founditem')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
