# Generated by Django 4.2.7 on 2025-04-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_founditem_claimed_by_founditem_custody_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
