# Generated by Django 4.2.7 on 2025-04-12 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_founditem_ai_category_founditem_ai_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='submitter',
        ),
        migrations.AddField(
            model_name='founditem',
            name='submitter_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='founditem',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='founditem',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Submitter (optional)'),
        ),
    ]
