# Generated by Django 4.2.7 on 2025-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_lostitem_submitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='found_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
